"server only";

import { PinataSDK } from "pinata-web3";

export const pinata = new PinataSDK({
  pinataJwt:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJkOTE3YmRjYS00ZGZhLTRlODUtYmIzMC1hMmJlODFlZDFmOTEiLCJlbWFpbCI6InNlb2RvdWJsZW9vQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiIwNDA3MTBiNmEwMGViZjJkZDZjNyIsInNjb3BlZEtleVNlY3JldCI6IjliNDhmNDM0YzU5ZmEyNGQ4OWY3OTk2ZmVlNjE0YjkwMzQ5M2I0MjJiMzUwOWMyOTIzMjk5ZWU2YWYwZjQ2NjYiLCJleHAiOjE3NjAyODAzMDd9.E69NnqqfI8eFNFKU4qGUQqn3sDRxy-TjrhwerfCK0vs",
  pinataGateway: "maroon-magnetic-nightingale-229.mypinata.cloud",
});
